# Generated by Django 4.2.7 on 2023-11-06 16:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DauSach',
            fields=[
                ('ma_dau_sach', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ten_dau_sach', models.CharField(max_length=50)),
                ('tac_gia', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('ma_kh', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('hoten_kh', models.CharField(max_length=30)),
                ('dia_chi', models.CharField(max_length=50)),
                ('dien_thoai', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('so_tien_no', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PhieuNhapSach',
            fields=[
                ('ma_phieu_nhap', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ngay_nhap', models.DateField(auto_now_add=True)),
                ('tong_tien', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TheLoai',
            fields=[
                ('ma_the_loai', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ten_the_loai', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sach',
            fields=[
                ('ma_sach', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nha_xuat_ban', models.CharField(max_length=50)),
                ('nam_xuat_ban', models.IntegerField()),
                ('so_luong_ton', models.IntegerField()),
                ('gia_tien', models.FloatField()),
                ('ma_dau_sach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.dausach')),
            ],
        ),
        migrations.CreateModel(
            name='PhieuThuTien',
            fields=[
                ('ma_phieu_thu', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ngay_thu_tien', models.DateField(auto_now_add=True)),
                ('so_tien_thu', models.FloatField()),
                ('ma_kh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('ma_hoa_don', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ngay_lap', models.DateField(auto_now_add=True)),
                ('tong_tien', models.FloatField(blank=True)),
                ('so_tien_tra', models.FloatField()),
                ('ma_kh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.khachhang')),
            ],
        ),
        migrations.AddField(
            model_name='dausach',
            name='ma_the_loai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookstore.theloai'),
        ),
        migrations.CreateModel(
            name='CT_PNS',
            fields=[
                ('mact_pns', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('so_luong_nhap', models.IntegerField()),
                ('don_gia_nhap', models.FloatField()),
                ('thanh_tien', models.FloatField(blank=True)),
                ('ma_phieu_nhap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.phieunhapsach')),
                ('ma_sach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.sach')),
            ],
        ),
        migrations.CreateModel(
            name='CT_HD',
            fields=[
                ('mact_hd', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('so_luong_ban', models.IntegerField()),
                ('don_gia_ban', models.FloatField()),
                ('thanh_tien', models.FloatField(blank=True)),
                ('ma_hoa_don', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.hoadon')),
                ('ma_sach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.sach')),
            ],
        ),
        migrations.CreateModel(
            name='BC_TON',
            fields=[
                ('mabc_ton', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('thang', models.IntegerField()),
                ('nam', models.IntegerField()),
                ('ton_dau', models.IntegerField()),
                ('phat_sinh', models.IntegerField()),
                ('ton_cuoi', models.IntegerField()),
                ('ma_sach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.sach')),
            ],
        ),
        migrations.CreateModel(
            name='BC_CONGNO',
            fields=[
                ('mabc_cn', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('thang', models.IntegerField()),
                ('nam', models.IntegerField()),
                ('no_dau', models.FloatField()),
                ('phat_sinh', models.FloatField()),
                ('no_cuoi', models.FloatField()),
                ('ma_kh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.khachhang')),
            ],
        ),
    ]
