# Generated by Django 4.2.7 on 2023-11-19 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DauSach',
            fields=[
                ('ma_dau_sach', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('ten_dau_sach', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('ma_kh', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('hoten_kh', models.CharField(blank=True, max_length=30, null=True)),
                ('dia_chi', models.CharField(blank=True, max_length=50, null=True)),
                ('dien_thoai', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('so_tien_no', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhieuNhapSach',
            fields=[
                ('ma_phieu_nhap', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('ngay_nhap', models.DateField(auto_now_add=True)),
                ('tong_tien', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TacGia',
            fields=[
                ('ma_tac_gia', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('ten_tac_gia', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='THAMSO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_nhap_toi_thieu', models.IntegerField(blank=True, default=150, null=True)),
                ('sl_ton_toi_da', models.IntegerField(blank=True, default=299, null=True)),
                ('so_tien_no_toi_da', models.FloatField(blank=True, default=1000000, null=True)),
                ('sl_ton_toi_thieu_sau_ban', models.IntegerField(blank=True, default=20, null=True)),
                ('ti_le_tinh_don_gia_ban', models.FloatField(blank=True, default=1.05, null=True)),
                ('kiem_tra_so_tien_thu', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TheLoai',
            fields=[
                ('ma_the_loai', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('ten_the_loai', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sach',
            fields=[
                ('ma_sach', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nha_xuat_ban', models.CharField(blank=True, max_length=50, null=True)),
                ('nam_xuat_ban', models.IntegerField(blank=True, null=True)),
                ('so_luong_ton', models.IntegerField(blank=True, null=True)),
                ('gia_tien', models.FloatField(blank=True, null=True)),
                ('ma_dau_sach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookstore.dausach')),
            ],
        ),
        migrations.CreateModel(
            name='PhieuThuTien',
            fields=[
                ('ma_phieu_thu', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('ngay_thu_tien', models.DateField(auto_now_add=True)),
                ('so_tien_thu', models.FloatField(blank=True, null=True)),
                ('ma_kh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookstore.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('ma_hoa_don', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('ngay_lap', models.DateField(auto_now_add=True)),
                ('tong_tien', models.FloatField(blank=True, null=True)),
                ('so_tien_tra', models.FloatField(blank=True, null=True)),
                ('con_lai', models.FloatField(blank=True, null=True)),
                ('ma_kh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookstore.khachhang')),
            ],
        ),
        migrations.AddField(
            model_name='dausach',
            name='ma_the_loai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookstore.theloai'),
        ),
        migrations.CreateModel(
            name='CT_TACGIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_dau_sach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookstore.dausach')),
                ('ma_tac_gia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookstore.tacgia')),
            ],
        ),
        migrations.CreateModel(
            name='CT_PNS',
            fields=[
                ('mact_pns', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('so_luong_nhap', models.IntegerField(blank=True, null=True)),
                ('don_gia_nhap', models.FloatField(blank=True, null=True)),
                ('thanh_tien', models.FloatField(blank=True, null=True)),
                ('ma_phieu_nhap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookstore.phieunhapsach')),
                ('ma_sach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookstore.sach')),
            ],
        ),
        migrations.CreateModel(
            name='CT_HD',
            fields=[
                ('mact_hd', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('so_luong_ban', models.IntegerField(blank=True, null=True)),
                ('don_gia_ban', models.FloatField(blank=True, null=True)),
                ('thanh_tien', models.FloatField(blank=True, null=True)),
                ('ma_hoa_don', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookstore.hoadon')),
                ('ma_sach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookstore.sach')),
            ],
        ),
        migrations.CreateModel(
            name='BC_TON',
            fields=[
                ('mabc_ton', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('thang', models.IntegerField(blank=True, null=True)),
                ('nam', models.IntegerField(blank=True, null=True)),
                ('ton_dau', models.IntegerField(blank=True, null=True)),
                ('phat_sinh', models.IntegerField(blank=True, null=True)),
                ('ton_cuoi', models.IntegerField(blank=True, null=True)),
                ('ma_sach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookstore.sach')),
            ],
        ),
        migrations.CreateModel(
            name='BC_CONGNO',
            fields=[
                ('mabc_cn', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('thang', models.IntegerField(blank=True, null=True)),
                ('nam', models.IntegerField(blank=True, null=True)),
                ('no_dau', models.FloatField(blank=True, null=True)),
                ('phat_sinh', models.FloatField(blank=True, null=True)),
                ('no_cuoi', models.FloatField(blank=True, null=True)),
                ('ma_kh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookstore.khachhang')),
            ],
        ),
        migrations.AddConstraint(
            model_name='ct_tacgia',
            constraint=models.UniqueConstraint(fields=('ma_dau_sach', 'ma_tac_gia'), name='unique_ct_tacgia'),
        ),
    ]
