# Generated by Django 4.2.7 on 2023-11-20 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ct_tacgia',
            name='unique_ct_tacgia',
        ),
    ]
