# Generated by Django 4.2.7 on 2023-12-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_sach_tac_gia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sach',
            name='tac_gia',
        ),
        migrations.AddField(
            model_name='dausach',
            name='tac_gia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
