# Generated by Django 4.2.7 on 2023-12-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_remove_dausach_tac_gia_sach_tac_gia'),
    ]

    operations = [
        migrations.AddField(
            model_name='sach',
            name='hinh_anh',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
